kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
  namespace: monitoring
spec:
  storageClassName: ceph-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
