apiVersion: v1
kind: Service
metadata:
  name: redis-manager-service
  namespace: wuda
  labels:
    app: redis-manager
spec:
  ports:
  - name: redis-port
    port: 6379
  clusterIP: None
  selector:
    app: redis-manager
    appCluster: redis-cluster
